--where 조건절
SELECT * FROM EMPLOYEES WHERE JOB_ID='IT_PROG';
SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE FIRST_NAME = 'David';
SELECT * FROM EMPLOYEES WHERE SALARY >= 15000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID <> 90;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE = '06/03/07'; -- 날짜 비교도 문자열로 비교한다.
SELECT * FROM EMPLOYEES WHERE HIRE_DATE >= '06/03/07'; -- 문자도 대소비교가 된다.


-- BETWEEN AND 연산자 ~ 사이에 (이상 이하)
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 10000;

-- IN 연산자
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (50,60,70);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'ST_MAN');

-- LIKE 연산자 - 검색에 사용됨, 리터럴 문자 % _ 사용
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '03%'; -- 03 으로 시작
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03'; -- 03 으로 끝
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03%'; -- 03 포함
SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE '%MAN%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_a'; -- 2글자인 사람
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_a%'; -- 2 번째 글자가 a인 사람

-- NULL 값 찾기
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

-- AND, OR - AND 가 OR 보다 빠름
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'FI_MCR');
SELECT * FROM EMPLOYEES WHERE JOB_ID ='IT_PROG' OR JOB_ID = 'FI_MCR';
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR SALARY >= 5000;
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' AND SALARY >= 5000;
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR' AND SALARY >= 6000; -- AND 먼저 동작
SELECT * FROM EMPLOYEES WHERE (JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR') AND SALARY >= 6000; -- OR 먼저 동작

-- NOT 부정의 의미 - 연산키워드와 같이 사용
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (50, 60);
SELECT * FROM EMPLOYEES WHERE JOB_ID NOT LIKE '%MAN%';
