SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;

SELECT FIRST_NAME, HIRE_DATE, EMAIL, SALARY FROM EMPLOYEES;

-- 컬럼명 자리에서는 연산이 된다.
-- 앨리어스 AS (별칭)
-- 생략, ""로 표현 가능
SELECT FIRST_NAME AS 별칭, SALARY 급여, SALARY + SALARY*0.1 "최종 급여" FROM EMPLOYEES;

-- NULL 확인
-- PK 는 EMPLOYEEE_ID, FK는 DEPARTMENT_ID
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NULL;

-- 문자열 연결 ||
-- ' ' 안에서 ''를 쓰고 싶다면 두번 쓴다.
SELECT FIRST_NAME || '님의 급여는 ' || SALARY || '$ 입니다.' AS 급여 FROM EMPLOYEES;

-- 중복제거 DISTINCT
SELECT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

-- ROWNUM (조회된 순서, 아주 중요), ROWID (행의 주소, 레코드가 저장된 위치)
SELECT EMPLOYEE_ID, FIRST_NAME, ROWNUM, ROWID FROM EMPLOYEES;