-- INSERT 
-- 테이블 구조를 빠르게 확인하는 방법
DESC EMPLOYEES; -- DESCRIPT 약자

INSERT INTO DEPARTMENTS VALUES(280, 'DEVELOPER', NULL, 1700);
SELECT * FROM DEPARTMENTS;

-- DML문은 트랜잭션이 항상 기록되는데, ROLLBACK이용해서 되돌릴 수 있다.
ROLLBACK;

-- 2ND (컬럼명만 지정 가능)
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID) VALUES(280, 'DEVELOPER', 1700);
ROLLBACK;

-- INSERT 구문도 서브쿼리 된다. (많이 사용하지는 않음)
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME) 
       VALUES ((SELECT MAX(DEPARTMENT_ID) FROM DEPARTMENTS)+10, 'DEV');
ROLLBACK;

-- INSERT 구문의 서브쿼리 (여러 값)
CREATE TABLE EMPS AS (SELECT * FROM EMPLOYEES WHERE 1=2); -- 테이블 구조 복사
SELECT * FROM EMPS;
INSERT INTO EMPS(EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID)
(SELECT EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID FROM EMPLOYEES WHERE JOB_ID='SA_MAN');
SELECT*FROM EMPS;
COMMIT; -- 트랜잭션을 반영함

-----------------------------------------------------------------------------
-- UPDATE
-- 업데이트 구문 사용 전, SELECT로 해당 값이 고유한지 확인후 업데이트
UPDATE EMPS SET SALARY=1000, COMMISSION_PCT=0.1 WHERE EMPLOYEE_ID=148; -- KEY를 조건에 적는 것이 일반적
SELECT * FROM EMPS;
UPDATE EMPS SET SALARY=NVL(SALARY, 0) +1000 WHERE EMPLOYEE_ID >= 145;

-- 업데이트 구문의 서브쿼리
-- 1ST (단일값 서브쿼리)
UPDATE EMPS SET SALARY = (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=100) WHERE EMPLOYEE_ID=148;

-- 2ND (여러값 서브쿼리)
UPDATE EMPS SET (SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) = 
(SELECT SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID=100) 
WHERE EMPLOYEE_ID=148;

-- 3RD (WHERE 절에도 가능)
UPDATE EMPS
SET SALARY = 1000
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE JOB_ID='IT_PROG');

