-- 트랜잭션
-- 오직 DML 문에 대해서만 트랜잭션을 수행할 수 있다.

-- 오토커밋 확인
SHOW AUTOCOMMIT;
-- 오토커밋 ON
SET AUTOCOMMIT ON;
-- 오토커밋 OFF
SET AUTOCOMMIT OFF;

----------------------
SELECT * FROM DEPTS;
DELETE FROM DEPTS WHERE DEPARTMENT_ID=10;
SAVEPOINT DEPT10; -- 세이브포인트 (트랜잭션 지점)
DELETE FROM DEPTS WHERE DEPARTMENT_ID=20;
SAVEPOINT DEPT20;
DELETE FROM DEPTS WHERE DEPARTMENT_ID=30;

-- 세이브포인트로 돌아가기
ROLLBACK TO DEPT20;
ROLLBACK TO DEPT10;
ROLLBACK;

INSERT INTO DEPTS VALUES (280, 'AA', NULL, 1800);
COMMIT; -- 데이터 반영
-- 트랜잭션 완료

-- 시험에선 트랜잭션 4원칙 ACID