-- 변환함수

-- 형변환함수
-- 자동형변환을 제공해준다. (문자와 숫자, 문자와 날짜)
SELECT * FROM EMPLOYEES WHERE SALARY >= '10000'; -- 문자 -> 숫자 자동 형변환
SELECT * FROM EMPLOYEES WHERE HIRE_DATE >= '08/01/01';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE >= '080101';

-- 강제형변환
-- TO_CHAR > 날짜를 문자
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD AM HH:MI:SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YY년 MM월 DD일') FROM DUAL; -- 년, 월, 일 은 날짜 포맷이 아니라 에러
SELECT TO_CHAR(SYSDATE, 'YY"년" MM"월" DD"일"') FROM DUAL; -- 날짜 포맷이 아닌 문자는 " "로 묶어준다

-- TO_CHAR > 숫자를 문자
SELECT TO_CHAR(20000, '999999999') AS RESULT FROM DUAL; -- 9자리 문자로 표현
SELECT TO_CHAR(20000, '099999999') AS RESULT FROM DUAL; -- 9자리, 빈자리 0으로 채움
SELECT TO_CHAR(20000, '999') AS RESULT FROM DUAL; -- 자리수가 부족하면 # 으로 처리된다.
SELECT TO_CHAR(20000.123, '999999.9999') AS RESULT FROM DUAL; -- 정수 6자리, 실수 4자리
SELECT TO_CHAR(20000, '$9999999') AS RESULT FROM DUAL;
SELECT TO_CHAR(200000, 'L9,999,999') AS RESULT FROM DUAL;

-- 오늘 환율 1372.17원, SALARY 값 원화로 표현
SELECT FIRST_NAME, TO_CHAR(SALARY * 1372.17, 'L999,999,999,999,999') AS WON FROM EMPLOYEES;

-- TO_DATE 문자를 날짜로
SELECT TO_DATE('2024 06 13', 'YYYY MM DD') FROM DUAL; -- 날짜 포맷에 맞춰 정확히 적으면 된다.
SELECT TO_DATE('20240613', 'YYYYMMDD') FROM DUAL;
SELECT SYSDATE-TO_DATE('20240613', 'YYYYMMDD') FROM DUAL;
SELECT TO_DATE('2024년 06월 13일', 'YYYY"년" MM"월" DD"일"') FROM DUAL; -- 날짜 포맷 문자 아니라면 " " 로 감싸준다.
SELECT TO_DATE('24-06-13 11시 30분 23초', 'YYYY-MM-DD HH"시" MI"분" SS"초"') FROM DUAL;

--
SELECT TO_CHAR(TO_DATE('240613', 'YYMMDD'), 'YYYY"년"MM"월"DD"일"') FROM DUAL;

-- TO_NUMBER 문자를 숫자로, 자동형변환 안될때 사용
SELECT '4000' - 3000 FROM DUAL; -- 자동형변환
SELECT '4,000' - 3000 FROM DUAL; -- 자동형변환 안됨
SELECT TO_NUMBER('4,000', '9,999') - 3000 FROM DUAL; -- 명시적 형변환 후 연산
SELECT TO_NUMBER() FROM DUAL;

-- NVL NULL 처리 함수
SELECT NVL (1000, 0), NVL(NULL, 0) FROM DUAL;
SELECT NULL + 1000 FROM DUAL; -- NULL 이 들어간 연산은 NULL 이 나옴

SELECT FIRST_NAME, SALARY, COMMISSION_PCT, SALARY + SALARY*NVL(COMMISSION_PCT, 0) AS TOTAL FROM EMPLOYEES;

-- NVL2 (대상값, 널이 아닌 경우, 널인경우)
SELECT NVL2(NULL, 'NOT NULL', 'YES NULL') FROM DUAL;
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, 
        NVL2(COMMISSION_PCT, SALARY + SALARY * COMMISSION_PCT, SALARY) AS TOTAL 
        FROM EMPLOYEES;

