-- 숫자 함수

-- ROUND 반올림
SELECT ROUND(45.923), ROUND(45.923, 1), ROUND(45.923, -1), ROUND(45.923, -2) FROM DUAL;

-- TRUNC 절삭
SELECT TRUNC(45.923), TRUNC(45.923, 2), TRUNC(45.923), TRUNC(45.923, -1) FROM DUAL;

-- ABS 절대값
-- CEIL 올림
-- FLOOR 내림
SELECT ABS(-45), CEIL(45.3), FLOOR(45.9) FROM DUAL;

-- MOD 나머지
SELECT 5/3, MOD(5,3) FROM DUAL;

-----------------------------------------------------------------------------------
-- 날짜 함수

-- SYSDATE 오늘 날짜
SELECT SYSDATE FROM DUAL; -- 년월일
SELECT SYSTIMESTAMP FROM DUAL; -- 년월일 시분초

-- 날짜는 연산 가능, DAY 기준으로 연산 된다.
SELECT HIRE_DATE, HIRE_DATE+18, HIRE_DATE-1 FROM EMPLOYEES;

SELECT FIRST_NAME, ROUND((SYSDATE - HIRE_DATE) / 7) FROM EMPLOYEES; -- 입사한 이후 몇 주?
SELECT FIRST_NAME, ROUND((SYSDATE - HIRE_DATE) / 365) FROM EMPLOYEES; -- 입사한 이후 몇 년?

-- 날짜의 반올림, 절삭
-- ROUND 정오 기준, TRUNC 일자 기준
SELECT ROUND(SYSDATE), TRUNC(SYSDATE) FROM DUAL;
SELECT ROUND(SYSDATE,'MONTH'), TRUNC(SYSDATE, 'MONTH') FROM DUAL; -- 달 기준
SELECT ROUND(SYSDATE,'YEAR'), TRUNC(SYSDATE, 'YEAR') FROM DUAL; -- 년 기준
