-- 문자열 함수
SELECT * FROM DUAL; -- DUAL : 가상 테이블, SQL문을 간단하게 연습하기 위함
SELECT LOWER('HELLO WORLD') FROM DUAL; 
SELECT LOWER(FIRST_NAME), UPPER(FIRST_NAME), INITCAP(FIRST_NAME) FROM EMPLOYEES;

-- 문자열 길이 LENGTH()
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES;
SELECT FIRST_NAME, INSTR(FIRST_NAME, 'a') FROM EMPLOYEES; -- a가 있는 위치 반환, 없으면 0 반환

-- 문자열 자르기
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 3) FROM EMPLOYEES; -- 3미만 절삭
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 3, 3) FROM EMPLOYEES; -- 3 부터 3글자

-- 문자열 합치기
SELECT FIRST_NAME || LAST_NAME FROM EMPLOYEES;
SELECT CONCAT(FIRST_NAME, LAST_NAME) FROM EMPLOYEES;

-- LPAD, RPAD - 범위 지정하고, 특정 문자로 채운다.
SELECT LPAD('ABC',10, '*') FROM DUAL;
SELECT LPAD(FIRST_NAME, 10, '*') FROM EMPLOYEES;
SELECT RPAD(FIRST_NAME, 10, '*') FROM EMPLOYEES;

-- LTRIM, RTRIM, TRIM - 문자열 공백 제거 또는 문자 삭제
SELECT TRIM('              HELLO WORLD               ') FROM DUAL;
SELECT LTRIM('              HELLO WORLD               ') FROM DUAL;
SELECT RTRIM('              HELLO WORLD               ') FROM DUAL;
SELECT LTRIM('HELLO WORLD', 'HEL') FROM DUAL;
SELECT RTRIM('HELLO WORLD', 'LD') FROM DUAL;

-- LTRIM, RTRIM 의 경우 중간에서 문자 삭제는 안된다.
SELECT LTRIM('HELLO WORLD', 'WOR') FROM DUAL;
SELECT RTRIM('HELLO WORLD', 'HEL') FROM DUAL;

-- REPLACE 문자열 변경
SELECT REPLACE('서울 대구 대전 부산 찍고', ' ', '->') FROM DUAL; -- 공백을 -> 로 변경
SELECT REPLACE('서울 대구 대전 부산 찍고', ' ', '') FROM DUAL; -- 공백 제거



