CREATE TABLE `Member` (
	`ID`	VARCHAR2(30)	NOT NULL,
	`NAME`	VARCHAR2(30)	NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `BOARD` (
	`NUM`	NUMBER(10)	NOT NULL,
	`TITLE`	VARCHAR2(100)	NULL,
	`CONTENT`	VARCHAR2(500)	NULL,
	`ID`	VARCHAR2(30)	NOT NULL
);

CREATE TABLE `REPLYBOARD` (
	`R_NUM`	NUMBER(10)	NOT NULL,
	`TITLE`	VARCHAR2(100)	NULL,
	`CONTENT`	VARCHAR2(500)	NULL,
	`ID`	VARCHAR2(30)	NOT NULL,
	`NUM`	NUMBER(10)	NOT NULL
);

CREATE TABLE `Admin` (
	`ID`	VARCHAR2(30)	NOT NULL,
	`REGDATE`	DATE	NULL
);

CREATE TABLE `COURSE` (
	`CNO`	NUMBER(20)	NOT NULL,
	`CTITLE`	VARCHAR2(30)	NULL,
	`CNAME`	VARCHAR2(50)	NULL
);

CREATE TABLE `COURSELIST` (
	`NUM`	NUMBER(10)	NOT NULL,
	`CNO`	NUMBER(20)	NOT NULL
);

ALTER TABLE `Member` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`ID`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`NUM`
);

ALTER TABLE `REPLYBOARD` ADD CONSTRAINT `PK_REPLYBOARD` PRIMARY KEY (
	`R_NUM`
);

ALTER TABLE `Admin` ADD CONSTRAINT `PK_ADMIN` PRIMARY KEY (
	`ID`
);

ALTER TABLE `COURSE` ADD CONSTRAINT `PK_COURSE` PRIMARY KEY (
	`CNO`
);

ALTER TABLE `Admin` ADD CONSTRAINT `FK_Member_TO_Admin_1` FOREIGN KEY (
	`ID`
)
REFERENCES `Member` (
	`ID`
);

